name: Minimal Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Upload project files
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        source: "."     # send everything
        target: "/home/ubuntu/minirider"

    - name: Restart PM2 apps
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/ubuntu/minirider/frontend
          npm install
          npm run build
          pm2 restart frontend || pm2 start npm --name frontend -- start

          cd /home/ubuntu/minirider/backend
          npm install
          pm2 restart backend || pm2 start npm --name backend -- start
