name: Deploy to Lightsail (Frontend & Backend)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v3

    - name: 📤 Upload frontend and backend
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        source: "./frontend,./backend"
        target: "/home/bitnami/minirider"
        rm: true
        strip_components: 1
        debug: true

    - name: 🚀 SSH and deploy with PM2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          export PATH=/opt/bitnami/nodejs/bin:$PATH

          cd /home/bitnami/minirider/backend
          npm install
          npx prisma generate
          npx prisma db push

          if pm2 describe backend > /dev/null; then
            pm2 restart backend
          else
            pm2 start npm --name backend -- start
          fi

          cd /home/bitnami/minirider/frontend
          npm install
          npm run build

          if pm2 describe frontend > /dev/null; then
            pm2 restart frontend
          else
            pm2 start npm --name frontend -- start
          fi

          pm2 save
